version: '3.7'
services:

  py-messenger:

    restart: always
    container_name: py-messenger

    hostname: localhost
#    image: py-messenger:1.0.0
    network_mode: host
    command: [ "python" ,"code/server.py"]
    build:
      dockerfile: Dockerfile
    environment:
      PORT: 8082


