version: '3.7'
services:

  py-messenger:
    restart: always
    container_name: py-messenger
    hostname: localhost
    network_mode: host
    command: [ "python" ,"code/server.py"]
    build:
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      PG_HOST: localhost
      PG_PORT: 5432
      PG_USERNAME: dbuser
      PG_PASSWORD: dbpass
      PG_DATABASE: python_messenger
